# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='title',
        ),
    ]
