# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170130_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('legend', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('full_img', models.CharField(blank=True, max_length=500, null=True)),
                ('external_link', models.CharField(blank=True, max_length=500, null=True)),
                ('legend', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Media',
            new_name='Video',
        ),
        migrations.AddField(
            model_name='galery',
            name='img_content',
            field=models.ManyToManyField(blank=True, related_name='galery_content', to='blog.Image'),
        ),
    ]
