# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170210_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='embed_link',
        ),
        migrations.AddField(
            model_name='video',
            name='http_link',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='iframe_link',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='source_site',
            field=models.CharField(choices=[('Youtube', 'youtube'), ('Vimeo', 'vimeo'), ('Other', 'iframe')], default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
