# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170212_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='http_link',
            new_name='source_id_string',
        ),
        migrations.RemoveField(
            model_name='video',
            name='iframe_link',
        ),
    ]
