# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170212_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='stat_video_at',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_up',
            field=models.ImageField(blank=True, null=True, upload_to='/static/blog/video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_site',
            field=models.CharField(choices=[('youtube', 'youtube'), ('youndcloud', 'soundcloud'), ('vimeo', 'vimeo'), ('other', 'iframe')], max_length=1000),
        ),
    ]
