# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170216_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='stat_video_at',
            new_name='start_video_at',
        ),
    ]
