# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170216_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_up',
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/video'),
        ),
    ]
